### ISSUE TITLE
Crystal 0.9.0

### ISSUE THREAD

**Issue by kbrock** [manastech/homebrew-crystal#10]
Wow, you all are super quick.

Is there a reason why this is downloading 0.9.0 source and recompiling rather than just downloading the osx release for 0.9.0?

Thanks

**Comment by waj** [comment]
I wanted to unify the procedure to install Crystal. Now the formula can also install the HEAD version and that requires compiling. Also, the precompiled version has some statically linked libraries. When you install the formula it also installs some dependencies and link to them dynamically, keeping the binaries a  bit smaller.

If you install from the main Homebrew repository (not this tap) without passing any flag, it will just download a precompiled "bottle" built on their servers for your OSX version.

In the long term, I'd like to see specific packages for each platform/distribution, and use the precompiled packages only to bootstrap them. We'll keep building those for standalone install as well.
