### ISSUE TITLE
Is this project still being used

### ISSUE THREAD

**Issue by jkthorne** [manastech/homebrew-crystal#19]
I am looking into the homebrew install and it looks like this is an unused project.  Can this be cleaned up or is it still in use?

**Comment by ghost** [comment]
This repository here has just been abandoned.

`brew update`
`brew info crystal` it show something like this:

```shell
crystal: stable 0.27.0 (bottled), HEAD
Fast and statically typed, compiled language with Ruby-like syntax
https://crystal-lang.org/
/usr/local/Cellar/crystal/0.27.0 (957 files, 50MB)
  Poured from bottle on 2018-12-26 at 14:30:26
/usr/local/Cellar/crystal/0.27.1 (966 files, 50.2MB) *
  Built from source on 2019-02-01 at 19:10:49
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/crystal.rb
==> Dependencies
Build: libatomic_ops ✔, pkg-config ✔
Required: bdw-gc ✔, gmp ✔, libevent ✔, libyaml ✔, llvm@6 ✔, pcre ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 905 (30 days), 4,248 (90 days), 14,204 (365 days)
install_on_request: 833 (30 days), 3,856 (90 days), 12,650 (365 days)
build_error: 0 (30 days)
```

If you've tapped in on old crystal tap then you can remove it easily.
`brew tap`
`brew untap <crystal-tap>` (replace <crystal-tap> with whatever you have for crystal. If you don't find a crystal deticated tap then you should be able to install the most recent crystal version.

If you are on Linux then I can tell you you can't use `brew` yet. Follow the regular Linux install instructions https://crystal-lang.org/reference/installation/
