### ISSUE TITLE
Cannot install crystal-lang because crystal formula cannot be found

### ISSUE THREAD

**Issue by agnoster** [manastech/homebrew-crystal#4]
```bash
$ brew tap manastech/crystal
==> Tapping manastech/crystal
...
$ brew install crystal-lang
==> Installing crystal-lang from manastech/homebrew-crystal
Error: No available formula for crystal
Searching formulae...
manastech/crystal/crystal-lang  manastech/crystal/libtask       manastech/crystal/micoro
Searching taps...
```

Possibly because of the `conflicts_with` directive?

**Comment by waj** [comment]
Did you try a `brew update` before install?

**Comment by agnoster** [comment]
Ah yup, that did it! Thanks! :-)

**Comment by agnoster** [comment]
(The docs at http://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html should probably be updated because it should be `brew install crystal-lang` now, correct?)

**Comment by waj** [comment]
Correct. As far as I know @asterite was about to fix it but he didn't push yet.
We had to change the name because another package named "crystal" was added to the official homebrew repository.

**Comment by agnoster** [comment]
Gotcha.

Just out of curiosity do they actually conflict (crystal-lang and crystal)? Or is it just to avoid people thinking they have the wrong package?

**Comment by waj** [comment]
Yes, because it also installs a "crystal" command.

**Comment by asterite** [comment]
Done! http://crystal-lang.org/docs/installation/on_mac_osx_using_homebrew.html

**Comment by agnoster** [comment]
@waj That's a pity :-/ Thanks for the help and the quick turnaround on the docs, looking forward to checking this cool-looking language out!
